query CartInput {
  cart {
    lines {
      id
      quantity
      cost {
        totalAmount { amount currencyCode }
      }
      merchandise {
        ... on ProductVariant {
          id
          price { amount }
          product {
            id
            collections(first: 250) { nodes { id } }
          }
        }
      }
    }
    buyerIdentity {
      isLoggedIn
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app:campaign", key: "config") {
      value
    }
  }
}
